name: Ping Render Every Minute

# Runs every 5 minutes
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Run loop every minute for 5 minutes
        run: |
          echo "Starting 5-minute loop at $(date)"
          for i in {1..5}; do
            echo "Pinging Render URL at $(date)"
            # Replace YOUR_RENDER_URL with your actual Render URL
            curl -s https://forex-owvr.onrender.com > /dev/null
            sleep 60
          done
          echo "Finished 5-minute loop at $(date)"
